services:
  - type: web
    name: finosage-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHONPATH
        value: .
      - key: ENVIRONMENT
        value: production
    cors:
      allowedOrigins:
        - https://finosage-frontend.vercel.app
        - https://finosage-backend.onrender.com